#!/bin/bash 
#PBS -l walltime=1:00:00 
#PBS -l mem=96GB 
#PBS -l ncpus=48 
#PBS -l jobfs=10GB 
#PBS -l storage=scratch/nf33+gdata/rv74+gdata/xp65+gdata/su28
#PBS -l other=hyperthread 
#PBS -q normal 
#PBS -P er8 
#PBS -o /home/548/cd3022/repos/GC26-combined-solar-wind/data/temp/solar-weatherfeatures/solar-weather-features_2020.oe 
#PBS -j oe 

cd /home/548/cd3022/repos/GC26-combined-solar-wind

python3 scripts/python/solar-weather-features.py 2020