#!/bin/bash 
#PBS -l walltime=1:00:00 
#PBS -l mem=96GB 
#PBS -l ncpus=48 
#PBS -l jobfs=10GB 
#PBS -l storage=scratch/nf33+gdata/w42+gdata/xp65+gdata/gb02+gdata/nf33
#PBS -l other=hyperthread 
#PBS -q normal 
#PBS -P nf33
#PBS -o /scratch/nf33/cd3022/GC26/wind-state-CF.oe
#PBS -j oe 

module use /g/data/xp65/public/modules
module load conda/analysis3

cd /home/548/cd3022/repos/GC26-combined-solar-wind

python3 scripts/python/state-based-REZ.py wind